### ISSUE TITLE
godep save ./... out of memory

### ISSUE THREAD

**Issue by tuxlinuxien** [tools/godep#434]
With:

- go 1.6
- godep v57 (linux/amd64/go1.6)

I have a project with less than 50 dependencies but it seems that 4GB of RAM + 2GB of swap are not enough  to run ` godep save ./...`

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x9bd9e0, 0x16)
	/usr/local/go/src/runtime/panic.go:530 +0x90
runtime.sysMap(0xc9464c0000, 0x498c0000, 0x45da00, 0xbea8d8)
	/usr/local/go/src/runtime/mem_linux.go:206 +0x9b
runtime.(*mheap).sysAlloc(0xbd0b00, 0x498c0000, 0xc820000180)
	/usr/local/go/src/runtime/malloc.go:429 +0x191
runtime.(*mheap).grow(0xbd0b00, 0x24c60, 0x0)
	/usr/local/go/src/runtime/mheap.go:651 +0x63
runtime.(*mheap).allocSpanLocked(0xbd0b00, 0x24c5f, 0xc819677000)
	/usr/local/go/src/runtime/mheap.go:553 +0x4f6
runtime.(*mheap).alloc_m(0xbd0b00, 0x24c5f, 0xffffff0100000000, 0x7f28e932edd0)
	/usr/local/go/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7f28e932ede8)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0xbd0b00, 0x24c5f, 0x10100000000, 0x43fdac)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0x498be000, 0x0, 0x0)
	/usr/local/go/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/usr/local/go/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0xc82001b500)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc820114ab0 sp=0xc820114aa8
runtime.mallocgc(0x498be000, 0x7ff760, 0x0, 0xc8f311f4a0)
	/usr/local/go/src/runtime/malloc.go:665 +0x9eb fp=0xc820114b88 sp=0xc820114ab0
runtime.newarray(0x7ff760, 0x498be00, 0x43cc98)
	/usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc820114bc8 sp=0xc820114b88
runtime.growslice(0x7ee8c0, 0xc90b750000, 0x3ad6400, 0x3ad6400, 0x3ad6401, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:100 +0x2c1 fp=0xc820114c38 sp=0xc820114bc8
main.findDirForPath(0xc8203c17d1, 0xe, 0xc8203b9c00, 0x0, 0x0, 0x0, 0x0)
	/home/yoann/.go/src/github.com/tools/godep/list.go:195 +0xb2f fp=0xc820114f58 sp=0xc820114c38
main.listPackage(0xc82010beb4, 0x5, 0x1, 0x0, 0x0)
	/home/yoann/.go/src/github.com/tools/godep/list.go:140 +0xca7 fp=0xc820115298 sp=0xc820114f58
main.LoadPackages(0xc82000a2c0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/yoann/.go/src/github.com/tools/godep/pkg.go:46 +0x2d7 fp=0xc8201153d0 sp=0xc820115298
main.save(0xc82000a2c0, 0x1, 0x1, 0x0, 0x0)
	/home/yoann/.go/src/github.com/tools/godep/save.go:143 +0x9fa fp=0xc820115c50 sp=0xc8201153d0
main.runSave(0xbc7160, 0xc82000a2c0, 0x1, 0x1)
	/home/yoann/.go/src/github.com/tools/godep/save.go:79 +0x142 fp=0xc820115ce8 sp=0xc820115c50
main.main()
	/home/yoann/.go/src/github.com/tools/godep/main.go:140 +0xdf1 fp=0xc820115f40 sp=0xc820115ce8
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc820115f90 sp=0xc820115f40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820115f98 sp=0xc820115f90

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
```

**Comment by freeformz** [comment]
That shouldn't happen. Can you provide the output of 'godep save -d -v ./... &> log'? It will be large thought. I suspect you somehow got into an infinite loop and I need the debug output to figure out where/why that happened.

**Comment by Sironfoot** [comment]
I'm having a similar problem. godep save just hangs. If I run "godep save -d -v ./... &> log" I end up with a 100MB log file after just a couple of seconds. Well, here is an abridged version of that log file if it helps:

```
versionString() godep v57 (darwin/amd64/go1.6)
majorGoVersion go1.6
VendorExperiment true
sep /vendor/
dotPackageImportPath: dominic/godep-test
dotPackageDir: /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test
godep: Go Version: go1.6
godep: No old Godeps.json found.
godep: Finding dependencies for [./...]
LoadPackages [./...]
listPackage ./.
findDirForPath ./. <nil>
Filling package: dominic/godep-test from /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test
/Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test/main.go
Looking For Package: ./. in /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test
&build.Package{
    Dir:            "/Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test",
    Name:           "",
    ImportComment:  "",
    Doc:            "",
    ImportPath:     "dominic/godep-test",
    Root:           "/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode",
    SrcRoot:        "/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src",
    PkgRoot:        "/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/pkg",
    PkgTargetRoot:  "",
    BinDir:         "/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/bin",
    Goroot:         false,
    PkgObj:         "",
    AllTags:        nil,
    ConflictDir:    "",
    GoFiles:        {"main.go"},
    CgoFiles:       nil,
    IgnoredGoFiles: nil,
    InvalidGoFiles: nil,
    CFiles:         nil,
    CXXFiles:       nil,
    MFiles:         nil,
    HFiles:         nil,
    SFiles:         nil,
    SwigFiles:      nil,
    SwigCXXFiles:   nil,
    SysoFiles:      nil,
    CgoCFLAGS:      nil,
    CgoCPPFLAGS:    nil,
    CgoCXXFLAGS:    nil,
    CgoLDFLAGS:     nil,
    CgoPkgConfig:   nil,
    Imports:        {"fmt", "github.com/gorilla/mux", "net/http"},
    ImportPos:      {},
    TestGoFiles:    nil,
    TestImports:    nil,
    TestImportPos:  {},
    XTestGoFiles:   nil,
    XTestImports:   nil,
    XTestImportPos: {},
}
Adding pc: /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test fat
Adding pc: /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test github.com/gorilla/mux
Adding pc: /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test net/http
Processing import fmt for /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test
findDirForPath fmt &{/Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test    dominic/godep-test /Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode /Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src /Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/pkg  /Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/bin false  []  [main.go] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [fmt github.com/gorilla/mux net/http] map[] [] [] map[] [] [] map[]}
resolving vendor posibilities: /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test /Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode
Adding search dir: /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test/vendor/fmt
Adding search dir: /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/vendor/fmt
Adding search dir: /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/vendor/fmt
Adding search dir: /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/vendor/fmt
Adding search dir: /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/vendor/fmt
Adding search dir: /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/vendor/fmt
Adding search dir: /Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/vendor/fmt
Adding search dir: /Volumes/Macintosh HD/Users/sironfoot/vendor/fmt
Adding search dir: /Volumes/Macintosh HD/Users/vendor/fmt
Adding search dir: /Volumes/Macintosh HD/vendor/fmt
Adding search dir: /Volumes/vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
Adding search dir: /vendor/fmt
...snip...

```

`Adding search dir: /vendor/fmt` just repeats over and over again for 1000's of lines.

**Comment by freeformz** [comment]
Thank you, that will help tremendously.

**Comment by freeformz** [comment]
@Sironfoot Your home directory is symlinked into your Dropbox folder? 
What is your version of godep (`godep version`). If you are not on v57+, please upgrade (`go get -u github.com/tools/godep`) and try again, providing any log (if it's different).

Also, what is your `echo $GOPATH` and `pwd` when you run `godep save` and ends up in the loop.

**Comment by Sironfoot** [comment]
```
$: godep version
godep v57 (darwin/amd64/go1.6)
```

```
$: echo $GOPATH
/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode
```

```
$: pwd
/Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test
```


I don't believe the folder "Dropbox (Personal)" is symlinked, I think that's the actual folder name. Is there a way to tell? Here's what it looks like in Finder...

<img width="590" alt="screen shot 2016-03-14 at 22 55 17" src="https://cloud.githubusercontent.com/assets/614728/13762614/ff50295a-ea37-11e5-9779-db2d54ce6edb.png">

**Comment by freeformz** [comment]
AFAICT your home directory is in dropbox, and it looks symlinked to /Users. What is the output of `echo $HOME`?.

**Comment by tuxlinuxien** [comment]
@freeformz I have tried to reproduce this bug but I didn't succeed.

However, since I am in china, some go related repositories are blocked by the Great Firewall. I am now running on a full VPN network and I it works well.

**Comment by Sironfoot** [comment]
```
$: echo $HOME
/Users/sironfoot
```

My Dropbox directory is in my home directory i.e. /User/sironfoot/Dropbox (Personal) and my go path is in my Dropbox directory.

I'll try setting up a new gopath outside of Dropdown when I get home, to see if that fixes it. Might be something to do with spaces in folder names?

**Comment by Sironfoot** [comment]
OK, the above examples are on my desktop computer (iMac, OSX 10.11.3), but I've tried setting this up on my laptop (MacBookPro, OSX 10.11.3), and it works fine, Godeps and vendor folders are created correctly. I have everything setup in the exact same folder structure as before, the only difference is that echo $GOPATH gives a slightly different output. The outputs from all above commands on my laptop are:

```
$: godep version
godep v57 (darwin/amd64/go1.6)

$: echo $GOPATH
/Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/

$: pwd
/Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test

$: echo $HOME
/Users/sironfoot
```

Notice that the output of $GOPATH includes the disc drive volume part ("/Volumes/Macintosh HD") on my laptop where godep works fine. But on my desktop where godep is hanging, the volume bit is missing. Would this be significant? And I'm pretty certain that nothing is symlinked here!

**Comment by freeformz** [comment]
Yes. godep uses path based case-insensitive file system path matches. So when you are on your desktop, somehow when you open a terminal to run godep you aren't actually in your $GOPATH (`/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode`), you are instead in `/Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test`. Do you use a context menu in Finder to open a terminal? Or some other method? Basically, how did you get to `/Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test` instead of  `/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode/src/dominic/godep-test`

**Comment by Sironfoot** [comment]
@freeformz I'm not an expert on OSX file systems, but I believe the `/Volumes/Macintosh HD/` bit of the path is optional as it points to the hard drive. If you omit it, it just assumes the default system drive, which is "Macintosh HD" in my case.

For instance, if I open a terminal and run:

`cd "/Volumes/Macintosh HD/Users/sironfoot"`

or

`cd "/Users/sironfoot"`

...I'll end up in the same directory either way.

As for why my `$GOPATH` is missing /Volumes/Macintosh HD it's probably because I have a habit of drag 'n' dropping directories from Finder into a Terminal window, which causes Terminal to split out the full path as a string (super handy), but it seems to omit the /Volumes/Macintosh HD part for some reason.

**Comment by freeformz** [comment]
changing your $GOPATH to `/Volumes/Macintosh HD/Users/sironfoot/Dropbox (Personal)/Development/Tutorials/gocode` should solve the problem. I'm somewhat surprised all of the go tools work as well. I *do* need to track down why some symlink stuff works and some doesn't though.

**Comment by freeformz** [comment]
Closing issues before archiving. Thank You\!
